<a href="https://colab.research.google.com/github/NITHISH-S-V-7/Data-Science/blob/main/Student_DataSet_Filling_Null.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

FILLING NAN VALUES

In [4]:
d={
    'sid':[101,102,103,104,105,106,107,108,109,110],
    'name':['madhumitha','vishnu','shan','Dharshini','sanjay','vikki','sathvik','mohan','narine','sumanth'],
    'phno':['9368564289','5387562748','8705926384','9074892547','7803685732','5384628564','6755364854',np.nan,np.nan,np.nan],
    'city':['chennai',np.nan,'hyd','kolkata',np.nan,'kashmir',np.nan,'bhglr','vizag','delhi'],
    'Gender':['Female','Female',np.nan,'Female','Male','Male',np.nan,np.nan,'Male','Male'],
    'domain':['py','java','py',np.nan,np.nan,np.nan,np.nan,'py','py','py']

}
df=pd.DataFrame(d)
df

   sid        name        phno     city  Gender domain
0  101  madhumitha  9368564289  chennai  Female     py
1  102      vishnu  5387562748      NaN  Female   java
2  103        shan  8705926384      hyd     NaN     py
3  104   Dharshini  9074892547  kolkata  Female    NaN
4  105      sanjay  7803685732      NaN    Male    NaN
5  106       vikki  5384628564  kashmir    Male    NaN
6  107     sathvik  6755364854      NaN     NaN    NaN
7  108       mohan         NaN    bhglr     NaN     py
8  109      narine         NaN    vizag    Male     py
9  110     sumanth         NaN    delhi    Male     py

In [5]:
#Fill nan values in phno

df['phno']=df['phno'].fillna('Nat available')
df

   sid        name           phno     city  Gender domain
0  101  madhumitha     9368564289  chennai  Female     py
1  102      vishnu     5387562748      NaN  Female   java
2  103        shan     8705926384      hyd     NaN     py
3  104   Dharshini     9074892547  kolkata  Female    NaN
4  105      sanjay     7803685732      NaN    Male    NaN
5  106       vikki     5384628564  kashmir    Male    NaN
6  107     sathvik     6755364854      NaN     NaN    NaN
7  108       mohan  Nat available    bhglr     NaN     py
8  109      narine  Nat available    vizag    Male     py
9  110     sumanth  Nat available    delhi    Male     py

In [6]:
#filling nan values in city

df['city']=df['city'].fillna('unknown')
df

   sid        name           phno     city  Gender domain
0  101  madhumitha     9368564289  chennai  Female     py
1  102      vishnu     5387562748  unknown  Female   java
2  103        shan     8705926384      hyd     NaN     py
3  104   Dharshini     9074892547  kolkata  Female    NaN
4  105      sanjay     7803685732  unknown    Male    NaN
5  106       vikki     5384628564  kashmir    Male    NaN
6  107     sathvik     6755364854  unknown     NaN    NaN
7  108       mohan  Nat available    bhglr     NaN     py
8  109      narine  Nat available    vizag    Male     py
9  110     sumanth  Nat available    delhi    Male     py

In [9]:
#Filling nan values in Gender

#df['Gender']=df['Gender'].fillna('unknown')

df['Gender'].mode()

df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])
df

   sid        name           phno     city  Gender domain
0  101  madhumitha     9368564289  chennai  Female     py
1  102      vishnu     5387562748  unknown  Female   java
2  103        shan     8705926384      hyd    Male     py
3  104   Dharshini     9074892547  kolkata  Female    NaN
4  105      sanjay     7803685732  unknown    Male    NaN
5  106       vikki     5384628564  kashmir    Male    NaN
6  107     sathvik     6755364854  unknown    Male    NaN
7  108       mohan  Nat available    bhglr    Male     py
8  109      narine  Nat available    vizag    Male     py
9  110     sumanth  Nat available    delhi    Male     py

In [10]:
#Filling nan values in donain
df['domain']=df['domain'].fillna(df['domain'].mode()[0])
df

   sid        name           phno     city  Gender domain
0  101  madhumitha     9368564289  chennai  Female     py
1  102      vishnu     5387562748  unknown  Female   java
2  103        shan     8705926384      hyd    Male     py
3  104   Dharshini     9074892547  kolkata  Female     py
4  105      sanjay     7803685732  unknown    Male     py
5  106       vikki     5384628564  kashmir    Male     py
6  107     sathvik     6755364854  unknown    Male     py
7  108       mohan  Nat available    bhglr    Male     py
8  109      narine  Nat available    vizag    Male     py
9  110     sumanth  Nat available    delhi    Male     py

FILLING NAN VALUES USING FORWARD AND BACKWARD FILL

In [12]:
d={
    'sid':[101,102,103,104,105,106,107,108,109,110],
    'name':['madhumitha','vishnu','shan','Dharshini','sanjay','vikki','sathvik','mohan','narine','sumanth'],
    'city':['chennai',np.nan,'hyd','kolkata',np.nan,'kashmir',np.nan,'bhglr','vizag','delhi'],
    'Gender':['Female','Female',np.nan,'Female','Male','Male',np.nan,np.nan,'Male','Male'],
    'domain':['py','java','py',np.nan,np.nan,np.nan,np.nan,'py','py','py']

}
df=pd.DataFrame(d)
df

   sid        name     city  Gender domain
0  101  madhumitha  chennai  Female     py
1  102      vishnu      NaN  Female   java
2  103        shan      hyd     NaN     py
3  104   Dharshini  kolkata  Female    NaN
4  105      sanjay      NaN    Male    NaN
5  106       vikki  kashmir    Male    NaN
6  107     sathvik      NaN     NaN    NaN
7  108       mohan    bhglr     NaN     py
8  109      narine    vizag    Male     py
9  110     sumanth    delhi    Male     py

In [14]:
#Filling nan values in city (Forwards)

df['city']=df['city'].ffill()
df

   sid        name     city  Gender domain
0  101  madhumitha  chennai  Female     py
1  102      vishnu  chennai  Female   java
2  103        shan      hyd     NaN     py
3  104   Dharshini  kolkata  Female    NaN
4  105      sanjay  kolkata    Male    NaN
5  106       vikki  kashmir    Male    NaN
6  107     sathvik  kashmir     NaN    NaN
7  108       mohan    bhglr     NaN     py
8  109      narine    vizag    Male     py
9  110     sumanth    delhi    Male     py

In [17]:
#Filling nan values in Gender (Forward)

df['Gender']=df['Gender'].ffill()
df

   sid        name     city  Gender domain
0  101  madhumitha  chennai  Female     py
1  102      vishnu  chennai  Female   java
2  103        shan      hyd  Female     py
3  104   Dharshini  kolkata  Female    NaN
4  105      sanjay  kolkata    Male    NaN
5  106       vikki  kashmir    Male    NaN
6  107     sathvik  kashmir    Male    NaN
7  108       mohan    bhglr    Male     py
8  109      narine    vizag    Male     py
9  110     sumanth    delhi    Male     py

In [18]:
#Filling nan values in domain (Backward)

df['domain']=df['domain'].bfill()
df

   sid        name     city  Gender domain
0  101  madhumitha  chennai  Female     py
1  102      vishnu  chennai  Female   java
2  103        shan      hyd  Female     py
3  104   Dharshini  kolkata  Female     py
4  105      sanjay  kolkata    Male     py
5  106       vikki  kashmir    Male     py
6  107     sathvik  kashmir    Male     py
7  108       mohan    bhglr    Male     py
8  109      narine    vizag    Male     py
9  110     sumanth    delhi    Male     py